name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff
      - name: Python Lint
        run: ruff check .
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Node deps
        run: npm ci || npm i --package-lock-only && npm ci
      - name: JS Lint
        run: npm run lint
      - name: Django Tests
        env:
          DJANGO_SECRET_KEY: test
          DJANGO_DEBUG: "1"
          ALLOWED_HOSTS: "localhost,127.0.0.1"
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
          python manage.py test -v 2